---
-  name: Our first play
   hosts: futurerama:!farnsworth

   tasks:
           - name: Learning more about copy mod
             copy:

                     content: "Learning at 145 Chubb Way"
                     dest: secondfloor.txt
           - name: install steam locomotive on All machines
             apt:
                     name: sl
                     state: present
             become: yes

- name: Our Second Play
  hosts: farnsworth

  tasks:
          - name: Install steam locomotive on all HREL machines
            yum:
                    name: sl
                    state: present
            become: yes
