---
- name: Push a script to our host and run it
  hosts: futurama
  gather_facts: true

  tasks:

  - name: Run our python script
    script: /home/student/py/holamundo.py #script lives on the CONTROLLER! but exectues on the HOSTS
    args: 
      executable: python3
    register: results

  - name: What did holamundo produce
    debug:
      var: results
