---
- name: Ansible and RESTful interfaces
  hosts: localhost
  gather_facts: false

  vars:
          astros: "{{ lookup('url', 'http://api.open-notify.org/astros.json') }}"
          spacecowboys: []
          
  tasks:
          - name: Quick iss api checkup
            debug:
                    msg: "Today on the ISS are: {{ astros.people[0].name }}"

          - name: Loop through our data
            debug:
                    msg: "Loop across ISS data: {{ item }}"
            loop: "{{ astros.people }}"

          - name: Loop through our data and only display names of astros
            debug:
                    msg: "Astros names are: {{ item.name }}"
            loop: "{{ astros.people }}"

          - name: Create a new list of Astro names
            set_fact:
                    spacecowboys: "{{ astros.people|map(attribute='name')|list }}"
            
          - name: Did it work?
            debug:
                    msg: "{{ item.split()[0] }}"
            loop: "{{ spacecowboys }}"
